export default [
  { id: 'start_late', label: 'Starts late' },
  { id: 'over_lunch', label: 'Scheduled over lunch' },
  { id: 'connection_trouble', label: 'Connection troubles' },
  { id: 'useless_deck', label: 'Useless slide deck' },
  { id: 'no_one_did_anything', label: 'No one did what was promised last time' },
  { id: 'inside_jokes', label: 'Inside joke no one else gets' },
  { id: 'too_many_people', label: 'Too many people' },
  { id: 'couldve_been_email', label: 'Could easily have been an email' },
  { id: 'sexist_joke', label: 'Sexist joke out of nowhere' },
  { id: 'people_of_another_meeting', label: 'Waiting for people to join from another meeting' },
  { id: 'rehashing', label: 'Just a rehash of last meeting' },
  { id: 'consulting_nonattendees', label: 'Promises to consult non-invited colleagues' },
  { id: 'devils_advocate', label: '"Let me be devil\'s advocate here..."' },
  { id: 'another_meeting', label: '"We need to schedule another meeting"' },
  { id: 'eating', label: 'Loud eating' },
  { id: 'need_opinion', label: '"I needed a [job title] opinion"' },
  { id: 'covid', label: 'Discussions on COVID' },
  { id: 'overtime', label: 'Runs over time' },
  { id: 'unmute', label: 'Forgot to unmute' },
  { id: 'decision_not_shown_up', label: 'Decision maker doesn\'t show up' },
  { id: 'no_break', label: 'No break in a 1+ hour meeting' },
  { id: 'fails_to_share_screen', label: 'Presenter fails to share screen' },
  { id: 'no_agenda', label: 'No agenda, plan or topic' },
  { id: 'opinion_speech', label: '10 minute long opinion speech' },
  { id: 'cat_ass', label: 'Cat showing its ass like it\'s on Onlyfans' },
  { id: 'restart', label: 'Presenter needs to restart' },
  { id: 'oversharing', label: 'Oversharing' },
  { id: 'useless_breakout', label: 'Breakout groups but for pure bullshit' },
  { id: 'toilet_noises', label: 'Toilet noises' },
  { id: 'cant_access_docs', label: 'Can\'t access to document' },
  { id: 'no_notes', label: 'No one is taking notes' },
  { id: 'can_we_just_discuss', label: '"But can we just discuss [random unrelated thing]"' }
]
