import { nanoid } from 'nanoid'

export default [
  { id: nanoid(), label: 'Starts late' },
  { id: nanoid(), label: 'Scheduled over lunch' },
  { id: nanoid(), label: 'Connection troubles' },
  { id: nanoid(), label: 'Useless slide deck' },
  { id: nanoid(), label: 'No one did what was promised last time' },
  { id: nanoid(), label: 'Inside joke no one else gets' },
  { id: nanoid(), label: 'Too many people' },
  { id: nanoid(), label: 'Could easily have been an email' },
  { id: nanoid(), label: 'Sexist joke out of nowhere' },
  { id: nanoid(), label: 'Waiting for people to join from another meeting' },
  { id: nanoid(), label: 'Just a rehash of last meeting' },
  { id: nanoid(), label: 'Promises to consult non-invited colleagues' },
  { id: nanoid(), label: '"Let me be devil\'s advocate here..."' },
  { id: nanoid(), label: '"We need to schedule another meeting"' },
  { id: nanoid(), label: 'Loud eating' },
  { id: nanoid(), label: '"I needed a [job title] opinion"' },
  { id: nanoid(), label: 'Discussions on COVID' },
  { id: nanoid(), label: 'Runs over time' },
  { id: nanoid(), label: 'Forgot to unmute' },
  { id: nanoid(), label: 'Decision maker doesn\'t show up' },
  { id: nanoid(), label: 'No break in a 1+ hour meeting' },
  { id: nanoid(), label: 'Presenter fails to share screen' },
  { id: nanoid(), label: 'No agenda, plan or topic' },
  { id: nanoid(), label: '10 minute long opinion speech' },
  { id: nanoid(), label: 'Cat showing its ass like it\'s on Onlyfans' },
  { id: nanoid(), label: 'Presenter needs to restart' },
  { id: nanoid(), label: 'Oversharing' },
  { id: nanoid(), label: 'Breakout groups but for pure bullshit' },
  { id: nanoid(), label: 'Toilet noises' },
  { id: nanoid(), label: 'Can\'t access to document' },
  { id: nanoid(), label: 'No one is taking notes' },
  { id: nanoid(), label: '"But can we just discuss [random unrelated thing]"' }
]
